import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container":      "var(--color-on-secondary-container)",
        "tertiary-container":           "var(--color-tertiary-container)",
        "surface-container-low":        "var(--color-surface-container-low)",
        "on-tertiary":                  "var(--color-on-tertiary)",
        background:                     "var(--color-background)",
        "surface-container-highest":    "var(--color-surface-container-highest)",
        "on-secondary":                 "var(--color-on-secondary)",
        "primary-fixed-dim":            "var(--color-primary-fixed-dim)",
        "on-background":                "var(--color-on-background)",
        "on-primary-container":         "var(--color-on-primary-container)",
        "secondary-fixed":              "var(--color-secondary-fixed)",
        primary:                        "var(--color-primary)",
        "inverse-primary":              "var(--color-inverse-primary)",
        "tertiary-fixed":               "var(--color-tertiary-fixed)",
        tertiary:                       "var(--color-tertiary)",
        "surface-bright":               "var(--color-surface-bright)",
        "primary-fixed":                "var(--color-primary-fixed)",
        "on-tertiary-fixed":            "var(--color-on-tertiary-fixed)",
        secondary:                      "var(--color-secondary)",
        "on-error-container":           "var(--color-on-error-container)",
        error:                          "var(--color-error)",
        "on-tertiary-fixed-variant":    "var(--color-on-tertiary-fixed-variant)",
        "error-container":              "var(--color-error-container)",
        "inverse-on-surface":           "var(--color-inverse-on-surface)",
        "primary-container":            "var(--color-primary-container)",
        "on-primary":                   "var(--color-on-primary)",
        "inverse-surface":              "var(--color-inverse-surface)",
        "on-error":                     "var(--color-on-error)",
        "surface-container-high":       "var(--color-surface-container-high)",
        "on-surface":                   "var(--color-on-surface)",
        "on-secondary-fixed":           "var(--color-on-secondary-fixed)",
        outline:                        "var(--color-outline)",
        "on-primary-fixed":             "var(--color-on-primary-fixed)",
        "on-secondary-fixed-variant":   "var(--color-on-secondary-fixed-variant)",
        "surface-variant":              "var(--color-surface-variant)",
        "surface-container-lowest":     "var(--color-surface-container-lowest)",
        "on-surface-variant":           "var(--color-on-surface-variant)",
        surface:                        "var(--color-surface)",
        "secondary-container":          "var(--color-secondary-container)",
        "tertiary-fixed-dim":           "var(--color-tertiary-fixed-dim)",
        "surface-dim":                  "var(--color-surface-dim)",
        "outline-variant":              "var(--color-outline-variant)",
        "secondary-fixed-dim":          "var(--color-secondary-fixed-dim)",
        "surface-tint":                 "var(--color-surface-tint)",
        "surface-container":            "var(--color-surface-container)",
        "on-tertiary-container":        "var(--color-on-tertiary-container)",
        "on-primary-fixed-variant":     "var(--color-on-primary-fixed-variant)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body:     ["Inter", "system-ui", "sans-serif"],
        label:    ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
